title: Jenna Hayes Portfolio
description: Data & Product Analyst Portfolio | A/B Testing, Funnels, Feature Adoption, Campaign Performance

theme: minima
baseurl: ""
url: "https://alecia-code.github.io"
markdown: kramdown
permalink: pretty
